- name: Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "common.yml"
      paths: vars
  tags: motd

- name: Set system hostname
  hostname: name="{{ inventory_hostname }}"

- name: Upload public key
  authorized_key: user=root key="{{ item }}" 
  with_file: "{{ ssh_keys | list }}"
    

# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
- name: Root password
  user: name=root password={{ root_password }}
  
- name: User config | Tmux configuration
  copy: src=~/.tmux.conf dest=/root

- name: User config | .inputrc
  copy: src=inputrc dest=~/.inputrc

- name: Configuration of motd
  include: motd.yml
  tags: motd 
  
- name: Set timezone 
  timezone: name={{ timezone }}






### Software
- name: Software | Activate EPEL
  yum: pkg=epel-release state=installed
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  
- name: Software | Updata package cache
  apt: update_cache=yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" 
  
- name: Software | Ensure basic packages
  package: name={{ item }} state=latest
  with_items: "{{ default_packages | list }}"

- name: Software | enable automatic updates
  template: src=20auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Time | Enable automatic time updates
  service: name={{ ntpd_service }} enabled=True state=restarted

# Mail notification subsystem
- name: SMTP | Configure email alias for root user
  lineinfile: dest=/etc/aliases line="root:\t\t{{ ", ".join(smtp_admin.__class__.__name__ == 'AnsibleUnicode' and [smtp_admin] or smtp_admin)}}" regexp="^root" insertafter="^#.*root"
  register: smtp_alias
  tags: smtp
  
- name: SMTP | Update aliases hash
  shell: newaliases
  when: smtp_alias.changed
  tags: smtp
      
- include: "smtp-{{ smtp_type }}.yml"
  when: smtp_host is defined
  tags: smtp



### System performance
- name: System swappines 5% only
  sysctl: name=vm.swappiness value=5 state=present reload=yes sysctl_set=yes
  tags: system






### Service and security configuration
- name: SSH | Change SSH port
  lineinfile: dest=/etc/ssh/sshd_config regexp='^Port ' line='Port {{set_ssh_port|default(22)}}'
  notify:
      - restart sshd
      - restart firewall

- name: SSH | Install fail2ban if port 22
  package: name=fail2ban state=latest
  when: set_ssh_port|default(22) == 22

- name: SSH | Enable fail2ban if port 22
  service: name=fail2ban state=restarted enabled=yes
  when: set_ssh_port|default(22) == 22

- name: Firewall | Disabled firewalld
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution == 'CentOS'